server:
  service:
    type: ClusterIP
  nodeSelector:
    role: monitoring
  tolerations:
    - key: monitoring
      operator: Equal
      value: "true"
      effect: NoSchedule

repoServer:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: monitoring
      operator: Equal
      value: "true"
      effect: NoSchedule

controller:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: monitoring
      operator: Equal
      value: "true"
      effect: NoSchedule

applicationSet:
  nodeSelector:
    role: monitoring
  tolerations:
    - key: monitoring
      operator: Equal
      value: "true"
      effect: NoSchedule
