daemonset:
  enabled: true

filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log

    output.elasticsearch:
      hosts: ["elasticsearch-master.monitoring.svc.cluster.local:9200"]

service:
  type: ClusterIP

# OPTIONAL:
# Uncomment if you want filebeat ONLY on monitoring nodes
# nodeSelector:
#   role: monitoring
#
# tolerations:
# - key: monitoring
#   operator: Equal
#   value: "true"
#   effect: NoSchedule
